apiVersion: apps/v1
kind: Deployment
metadata:
  name: apihistoricogalaxy
spec:
  selector:
    matchLabels:
      app: apihistoricogalaxy
  replicas: 2
  template:
    metadata:
      labels:
        app: apihistoricogalaxy
    spec:
      containers:
      - name: apihistoricogalaxy
        env:
        - name: MongoServer
          value: "mongodb://facturadbaaron:jjKKULL0y4mz7xlQ4ogRF6bS9AfYEf0XeqypiClhAdJ3QKebiLV9lJYNUjcBfLopLoOYtQ9NOsn9FppOLBXH5w==@facturadbaaron.documents.azure.com:10255/?ssl=true&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@facturadbaaron@&retryWrites=false"
        - name: MongoDbname
          value: "ventasdb"
        - name: MongoColName
          value: "factura"
        - name: UrlSeguridad
          value: "http://apiseguridadgalaxy:8080/"
        - name: ApiNameSeguridad
          value: apihistorico
        - name: BusUrl
          value: "Endpoint=sb://busgalaxyaaron.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=39uqcbg+zkiLJ0NC/9D8D6rGH49cA8+fNwspceR0q8Y="
        - name: BusTopic
          value: pedidosender
        - name: BusSuscriptor
          value: facturahistorico
        image: aaronma/apihistoricogalaxy:1.0.0
        imagePullPolicy: Always        
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apihistoricogalaxy
  labels:
    app: apihistoricogalaxy
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http-traffic
  selector:
    app: apihistoricogalaxy
  type: LoadBalancer
