apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxyreversogalaxy
spec:
  selector:
    matchLabels:
      app: proxyreversogalaxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxyreversogalaxy
    spec:
      containers:
      - name: proxyreversogalaxy
        image: aaronma/proxyreversogalaxy:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: proxyreversogalaxy
  labels:
    app: proxyreversogalaxy
spec:
  ports:
    - port: 8095
      protocol: TCP
      targetPort: 8085
      name: http-traffic
  selector:
    app: proxyreversogalaxy
  type: LoadBalancer