apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisendergalaxy
spec:
  selector:
    matchLabels:
      app: apisendergalaxy
  replicas: 2
  template:
    metadata:
      labels:
        app: apisendergalaxy
    spec:
      containers:
      - name: apisendergalaxy
        env:
        - name: UrlSeguridad
          value: "http://apiseguridadgalaxy:8080/"
        - name: ApiNameSeguridad
          value: apisender
        - name: BusUrl
          value: "Endpoint=sb://busgalaxyayma.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=QhhQ9HUihfGSsrgx4sBw//ya7M8CSGb/DvlMW/ftjfk="
        - name: BusTopic
          value: pedidosender
        image: aaronma/apisendergalaxy:1.0.0
        imagePullPolicy: Always        
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apisendergalaxy
  labels:
    app: apisendergalaxy
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http-traffic
  selector:
    app: apisendergalaxy
  type: LoadBalancer
